# Generated by Django 4.2.7 on 2023-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length='100')),
                ('level', models.IntegerField(max_length=3)),
                ('load_capacity', models.IntegerField(max_length=5)),
                ('attack', models.IntegerField(max_length=9)),
                ('units', models.IntegerField(max_length=2)),
                ('city_level_required', models.IntegerField(max_length=2)),
            ],
        ),
    ]
