# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troops_calculator', '0002_alter_troop_attack_alter_troop_city_level_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('lane', models.TextField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='troop',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='troops_calculator.category'),
        ),
        migrations.AddField(
            model_name='troop',
            name='required_building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='troops_calculator.building'),
        ),
    ]
