# Generated by Django 4.2.7 on 2023-11-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troops_calculator', '0003_building_category_troop_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops_calculator.category'),
        ),
        migrations.AlterField(
            model_name='troop',
            name='required_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops_calculator.building'),
        ),
    ]
