# Generated by Django 4.2.7 on 2023-11-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troops_calculator', '0004_alter_troop_category_alter_troop_required_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='lane',
            new_name='row',
        ),
    ]
