# Generated by Django 4.2.7 on 2023-11-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops_calculator', '0006_rename_required_building_troop_min_building_lvl_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troop',
            name='city_level_required',
        ),
        migrations.AddField(
            model_name='category',
            name='building',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='troop',
            name='min_building_lvl_required',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
